# Getting Started {#intro}

## Installing R and Rstudio

1. Download R
2. Download RStudio

## Setting Up 

### Using the R version of packages from the SOA (include helper script)

You want to use the exact same code that will be on the Prometric Computers.  An R library is a software package that provides added flexibility.  R is open-source, which means that it is maintained by a community of developers on a volunteer basis.  

To change the library that R uses, use the `libPaths` function.  

```{r}
#.libPaths("C:/Users/sam.castillo/Desktop/PA/library/PAlibrary")
```

### Setting the R Version

This book uses Rv3.5.  To switch between R versions, 

Tools -> Global Options -> R Version -> Restart Rstudio

## R basic syntax

There are already hundreds of great tutorials online.  This will only be a minimal version. 

## Data Types

Each object in R has a different type.  

- numeric 
- character 
- factors
- booleans

As well as classes

- matrix
- data frame
- tibble (just another name for a data frame)
- list (most important)

### Objects

### Functions 

### Just Copy Someone Elese's Tutorials

## Rmd file overview


## Read in a data file from local computer in csv format
