<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 7 Data exploration | Predictive Analytics for Actuaries</title>
  <meta name="description" content=" 7 Data exploration | Predictive Analytics for Actuaries" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content=" 7 Data exploration | Predictive Analytics for Actuaries" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 7 Data exploration | Predictive Analytics for Actuaries" />
  
  
  

<meta name="author" content="Sam Castillo" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/artificial_actuary_logo_favicon.png" type="image/x-icon" />
<link rel="prev" href="r-programming.html"/>
<link rel="next" href="introduction-to-modeling.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  { background-color: #f8f8f8; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Exam PA Study Manual</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="1" data-path="the-exam.html"><a href="the-exam.html"><i class="fa fa-check"></i><b>1</b> The exam</a></li>
<li class="chapter" data-level="2" data-path="prometric-demo.html"><a href="prometric-demo.html"><i class="fa fa-check"></i><b>2</b> Prometric Demo</a></li>
<li class="chapter" data-level="3" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>3</b> Introduction</a></li>
<li class="chapter" data-level="4" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>4</b> Getting started</a><ul>
<li class="chapter" data-level="4.1" data-path="getting-started.html"><a href="getting-started.html#download-the-data"><i class="fa fa-check"></i><b>4.1</b> Download the data</a></li>
<li class="chapter" data-level="4.2" data-path="getting-started.html"><a href="getting-started.html#download-islr"><i class="fa fa-check"></i><b>4.2</b> Download ISLR</a></li>
<li class="chapter" data-level="4.3" data-path="getting-started.html"><a href="getting-started.html#new-users"><i class="fa fa-check"></i><b>4.3</b> New users</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="what-do-you-need-to-know-in-order-to-pass.html"><a href="what-do-you-need-to-know-in-order-to-pass.html"><i class="fa fa-check"></i><b>5</b> What do you need to know in order to pass?</a><ul>
<li class="chapter" data-level="5.1" data-path="what-do-you-need-to-know-in-order-to-pass.html"><a href="what-do-you-need-to-know-in-order-to-pass.html#example-1---making-parameter-changes"><i class="fa fa-check"></i><b>5.1</b> Example 1 - Making parameter changes</a></li>
<li class="chapter" data-level="5.2" data-path="what-do-you-need-to-know-in-order-to-pass.html"><a href="what-do-you-need-to-know-in-order-to-pass.html#example-2---data-exploration"><i class="fa fa-check"></i><b>5.2</b> Example 2 - Data exploration</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="r-programming.html"><a href="r-programming.html"><i class="fa fa-check"></i><b>6</b> R programming</a><ul>
<li class="chapter" data-level="6.1" data-path="r-programming.html"><a href="r-programming.html#notebook-chunks"><i class="fa fa-check"></i><b>6.1</b> Notebook chunks</a></li>
<li class="chapter" data-level="6.2" data-path="r-programming.html"><a href="r-programming.html#basic-operations"><i class="fa fa-check"></i><b>6.2</b> Basic operations</a></li>
<li class="chapter" data-level="6.3" data-path="r-programming.html"><a href="r-programming.html#lists"><i class="fa fa-check"></i><b>6.3</b> Lists</a></li>
<li class="chapter" data-level="6.4" data-path="r-programming.html"><a href="r-programming.html#functions"><i class="fa fa-check"></i><b>6.4</b> Functions</a></li>
<li class="chapter" data-level="6.5" data-path="r-programming.html"><a href="r-programming.html#data-frames"><i class="fa fa-check"></i><b>6.5</b> Data frames</a></li>
<li class="chapter" data-level="6.6" data-path="r-programming.html"><a href="r-programming.html#pipes"><i class="fa fa-check"></i><b>6.6</b> Pipes</a></li>
<li class="chapter" data-level="6.7" data-path="r-programming.html"><a href="r-programming.html#the-soas-code-doesnt-use-pipes-or-dplyr-so-can-i-skip-learning-this"><i class="fa fa-check"></i><b>6.7</b> The SOA’s code doesn’t use pipes or dplyr, so can I skip learning this?</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>7</b> Data exploration</a><ul>
<li class="chapter" data-level="7.1" data-path="data-exploration.html"><a href="data-exploration.html#how-to-make-graphs-in-r"><i class="fa fa-check"></i><b>7.1</b> How to make graphs in R</a><ul>
<li class="chapter" data-level="7.1.1" data-path="data-exploration.html"><a href="data-exploration.html#add-a-plot"><i class="fa fa-check"></i><b>7.1.1</b> Add a plot</a></li>
<li class="chapter" data-level="7.1.2" data-path="data-exploration.html"><a href="data-exploration.html#data-manipulation-chaining"><i class="fa fa-check"></i><b>7.1.2</b> Data manipulation chaining</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="data-exploration.html"><a href="data-exploration.html#the-different-graph-types"><i class="fa fa-check"></i><b>7.2</b> The different graph types</a><ul>
<li class="chapter" data-level="7.2.1" data-path="data-exploration.html"><a href="data-exploration.html#histogram"><i class="fa fa-check"></i><b>7.2.1</b> Histogram</a></li>
<li class="chapter" data-level="7.2.2" data-path="data-exploration.html"><a href="data-exploration.html#box-plot"><i class="fa fa-check"></i><b>7.2.2</b> Box plot</a></li>
<li class="chapter" data-level="7.2.3" data-path="data-exploration.html"><a href="data-exploration.html#scatterplot"><i class="fa fa-check"></i><b>7.2.3</b> Scatterplot</a></li>
<li class="chapter" data-level="7.2.4" data-path="data-exploration.html"><a href="data-exploration.html#bar-charts"><i class="fa fa-check"></i><b>7.2.4</b> Bar charts</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="data-exploration.html"><a href="data-exploration.html#how-to-save-time-with-dplyr"><i class="fa fa-check"></i><b>7.3</b> How to save time with dplyr</a></li>
<li class="chapter" data-level="7.4" data-path="data-exploration.html"><a href="data-exploration.html#how-to-explore-the-data"><i class="fa fa-check"></i><b>7.4</b> How to explore the data</a></li>
<li class="chapter" data-level="7.5" data-path="data-exploration.html"><a href="data-exploration.html#how-to-transform-the-data"><i class="fa fa-check"></i><b>7.5</b> How to transform the data</a></li>
<li class="chapter" data-level="7.6" data-path="data-exploration.html"><a href="data-exploration.html#a-real-example"><i class="fa fa-check"></i><b>7.6</b> A real example</a><ul>
<li class="chapter" data-level="7.6.1" data-path="data-exploration.html"><a href="data-exploration.html#garbage-in-garbage-out"><i class="fa fa-check"></i><b>7.6.1</b> Garbage in; garbage out 🗑</a></li>
<li class="chapter" data-level="7.6.2" data-path="data-exploration.html"><a href="data-exploration.html#be-a-detective"><i class="fa fa-check"></i><b>7.6.2</b> Be a detective 🔎</a></li>
<li class="chapter" data-level="7.6.3" data-path="data-exploration.html"><a href="data-exploration.html#a-picture-is-worth-a-thousand-words"><i class="fa fa-check"></i><b>7.6.3</b> A picture is worth a thousand words 📷</a></li>
<li class="chapter" data-level="7.6.4" data-path="data-exploration.html"><a href="data-exploration.html#factor-or-numeric"><i class="fa fa-check"></i><b>7.6.4</b> Factor or numeric ❓</a></li>
<li class="chapter" data-level="7.6.5" data-path="data-exploration.html"><a href="data-exploration.html#of-statistics-are-false"><i class="fa fa-check"></i><b>7.6.5</b> 73.6% of statistics are false 🤯</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="data-exploration.html"><a href="data-exploration.html#exercises"><i class="fa fa-check"></i><b>7.7</b> Exercises</a></li>
<li class="chapter" data-level="7.8" data-path="data-exploration.html"><a href="data-exploration.html#answers-to-exercises"><i class="fa fa-check"></i><b>7.8</b> Answers to exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html"><i class="fa fa-check"></i><b>8</b> Introduction to modeling</a><ul>
<li class="chapter" data-level="8.1" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html#modeling-vocabulary"><i class="fa fa-check"></i><b>8.1</b> Modeling vocabulary</a></li>
<li class="chapter" data-level="8.2" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html#modeling-notation"><i class="fa fa-check"></i><b>8.2</b> Modeling notation</a></li>
<li class="chapter" data-level="8.3" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html#ordinary-least-squares-ols"><i class="fa fa-check"></i><b>8.3</b> Ordinary Least Squares (OLS)</a></li>
<li class="chapter" data-level="8.4" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html#r2-statistic"><i class="fa fa-check"></i><b>8.4</b> R^2 Statistic</a></li>
<li class="chapter" data-level="8.5" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html#correlation"><i class="fa fa-check"></i><b>8.5</b> Correlation</a><ul>
<li class="chapter" data-level="8.5.1" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html#pearsons-correlation"><i class="fa fa-check"></i><b>8.5.1</b> Pearson’s correlation</a></li>
<li class="chapter" data-level="8.5.2" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html#spearman-rank-correlation"><i class="fa fa-check"></i><b>8.5.2</b> Spearman (rank) correlation</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html#regression-vs.-classification"><i class="fa fa-check"></i><b>8.6</b> Regression vs. classification</a></li>
<li class="chapter" data-level="8.7" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html#regression-metrics"><i class="fa fa-check"></i><b>8.7</b> Regression metrics</a></li>
<li class="chapter" data-level="8.8" data-path="introduction-to-modeling.html"><a href="introduction-to-modeling.html#example"><i class="fa fa-check"></i><b>8.8</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html"><i class="fa fa-check"></i><b>9</b> Generalized linear Models (GLMs)</a><ul>
<li class="chapter" data-level="9.0.1" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html#assumptions-of-ols"><i class="fa fa-check"></i><b>9.0.1</b> Assumptions of OLS</a></li>
<li class="chapter" data-level="9.0.2" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html#assumptions-of-glms"><i class="fa fa-check"></i><b>9.0.2</b> Assumptions of GLMs</a></li>
<li class="chapter" data-level="9.1" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html#advantages-and-disadvantages"><i class="fa fa-check"></i><b>9.1</b> Advantages and disadvantages</a></li>
<li class="chapter" data-level="9.2" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html#glms-for-regression"><i class="fa fa-check"></i><b>9.2</b> GLMs for regression</a></li>
<li class="chapter" data-level="9.3" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html#interpretation-of-coefficients"><i class="fa fa-check"></i><b>9.3</b> Interpretation of coefficients</a><ul>
<li class="chapter" data-level="9.3.1" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html#identity-link"><i class="fa fa-check"></i><b>9.3.1</b> Identity link</a></li>
<li class="chapter" data-level="9.3.2" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html#log-link"><i class="fa fa-check"></i><b>9.3.2</b> Log link</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html#other-links"><i class="fa fa-check"></i><b>9.4</b> Other links</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="glms-for-classification.html"><a href="glms-for-classification.html"><i class="fa fa-check"></i><b>10</b> GLMs for classification</a><ul>
<li class="chapter" data-level="10.1" data-path="glms-for-classification.html"><a href="glms-for-classification.html#binary-target"><i class="fa fa-check"></i><b>10.1</b> Binary target</a></li>
<li class="chapter" data-level="10.2" data-path="glms-for-classification.html"><a href="glms-for-classification.html#count-target"><i class="fa fa-check"></i><b>10.2</b> Count target</a></li>
<li class="chapter" data-level="10.3" data-path="glms-for-classification.html"><a href="glms-for-classification.html#link-functions"><i class="fa fa-check"></i><b>10.3</b> Link functions</a></li>
<li class="chapter" data-level="10.4" data-path="glms-for-classification.html"><a href="glms-for-classification.html#interpretation-of-coefficients-1"><i class="fa fa-check"></i><b>10.4</b> Interpretation of coefficients</a><ul>
<li class="chapter" data-level="10.4.1" data-path="glms-for-classification.html"><a href="glms-for-classification.html#logit"><i class="fa fa-check"></i><b>10.4.1</b> Logit</a></li>
<li class="chapter" data-level="10.4.2" data-path="glms-for-classification.html"><a href="glms-for-classification.html#probit-cauchit-cloglog"><i class="fa fa-check"></i><b>10.4.2</b> Probit, Cauchit, Cloglog</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="glms-for-classification.html"><a href="glms-for-classification.html#example-1"><i class="fa fa-check"></i><b>10.5</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="classification-metrics.html"><a href="classification-metrics.html"><i class="fa fa-check"></i><b>11</b> Classification metrics</a><ul>
<li class="chapter" data-level="11.1" data-path="classification-metrics.html"><a href="classification-metrics.html#area-under-the-roc-curve-auc"><i class="fa fa-check"></i><b>11.1</b> Area Under the ROC Curve (AUC)</a></li>
<li class="chapter" data-level="11.2" data-path="classification-metrics.html"><a href="classification-metrics.html#additional-reading"><i class="fa fa-check"></i><b>11.2</b> Additional reading</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html"><i class="fa fa-check"></i><b>12</b> Additional GLM topics</a><ul>
<li class="chapter" data-level="12.1" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#residuals"><i class="fa fa-check"></i><b>12.1</b> Residuals</a><ul>
<li class="chapter" data-level="12.1.1" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#raw-residuals"><i class="fa fa-check"></i><b>12.1.1</b> Raw residuals</a></li>
<li class="chapter" data-level="12.1.2" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#deviance-residuals"><i class="fa fa-check"></i><b>12.1.2</b> Deviance residuals</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#example-2"><i class="fa fa-check"></i><b>12.2</b> Example</a></li>
<li class="chapter" data-level="12.3" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#log-transforms-of-predictors"><i class="fa fa-check"></i><b>12.3</b> Log transforms of predictors</a></li>
<li class="chapter" data-level="12.4" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#reference-levels"><i class="fa fa-check"></i><b>12.4</b> Reference levels</a></li>
<li class="chapter" data-level="12.5" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#interactions"><i class="fa fa-check"></i><b>12.5</b> Interactions</a></li>
<li class="chapter" data-level="12.6" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#offsets"><i class="fa fa-check"></i><b>12.6</b> Offsets</a></li>
<li class="chapter" data-level="12.7" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#tweedie-regression"><i class="fa fa-check"></i><b>12.7</b> Tweedie regression</a></li>
<li class="chapter" data-level="12.8" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#combinations-of-link-functions-and-target-distributions"><i class="fa fa-check"></i><b>12.8</b> Combinations of Link Functions and Target Distributions</a><ul>
<li class="chapter" data-level="12.8.1" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#gaussian-response-with-log-link"><i class="fa fa-check"></i><b>12.8.1</b> Gaussian Response with Log Link</a></li>
<li class="chapter" data-level="12.8.2" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#gaussian-response-with-inverse-link"><i class="fa fa-check"></i><b>12.8.2</b> Gaussian Response with Inverse Link</a></li>
<li class="chapter" data-level="12.8.3" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#gaussian-response-with-identity-link"><i class="fa fa-check"></i><b>12.8.3</b> Gaussian Response with Identity Link</a></li>
<li class="chapter" data-level="12.8.4" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#gaussian-response-with-log-link-and-negative-values"><i class="fa fa-check"></i><b>12.8.4</b> Gaussian Response with Log Link and Negative Values</a></li>
<li class="chapter" data-level="12.8.5" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#gamma-response-with-log-link"><i class="fa fa-check"></i><b>12.8.5</b> Gamma Response with Log Link</a></li>
<li class="chapter" data-level="12.8.6" data-path="additional-glm-topics.html"><a href="additional-glm-topics.html#gamma-with-inverse-link"><i class="fa fa-check"></i><b>12.8.6</b> Gamma with Inverse Link</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="glm-variable-selection.html"><a href="glm-variable-selection.html"><i class="fa fa-check"></i><b>13</b> GLM variable selection</a><ul>
<li class="chapter" data-level="13.1" data-path="glm-variable-selection.html"><a href="glm-variable-selection.html#stepwise-subset-selection"><i class="fa fa-check"></i><b>13.1</b> Stepwise subset selection</a></li>
<li class="chapter" data-level="13.2" data-path="glm-variable-selection.html"><a href="glm-variable-selection.html#penalized-linear-models"><i class="fa fa-check"></i><b>13.2</b> Penalized Linear Models</a></li>
<li class="chapter" data-level="13.3" data-path="glm-variable-selection.html"><a href="glm-variable-selection.html#ridge-regression"><i class="fa fa-check"></i><b>13.3</b> Ridge Regression</a></li>
<li class="chapter" data-level="13.4" data-path="glm-variable-selection.html"><a href="glm-variable-selection.html#lasso"><i class="fa fa-check"></i><b>13.4</b> Lasso</a></li>
<li class="chapter" data-level="13.5" data-path="glm-variable-selection.html"><a href="glm-variable-selection.html#elastic-net"><i class="fa fa-check"></i><b>13.5</b> Elastic Net</a></li>
<li class="chapter" data-level="13.6" data-path="glm-variable-selection.html"><a href="glm-variable-selection.html#advantages-and-disadvantages-1"><i class="fa fa-check"></i><b>13.6</b> Advantages and disadvantages</a></li>
<li class="chapter" data-level="13.7" data-path="glm-variable-selection.html"><a href="glm-variable-selection.html#example-ridge-regression"><i class="fa fa-check"></i><b>13.7</b> Example: Ridge Regression</a></li>
<li class="chapter" data-level="13.8" data-path="glm-variable-selection.html"><a href="glm-variable-selection.html#example-the-lasso"><i class="fa fa-check"></i><b>13.8</b> Example: The Lasso</a></li>
<li class="chapter" data-level="13.9" data-path="glm-variable-selection.html"><a href="glm-variable-selection.html#references"><i class="fa fa-check"></i><b>13.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="tree-based-models.html"><a href="tree-based-models.html"><i class="fa fa-check"></i><b>14</b> Tree-based models</a><ul>
<li class="chapter" data-level="14.1" data-path="tree-based-models.html"><a href="tree-based-models.html#decision-trees"><i class="fa fa-check"></i><b>14.1</b> Decision Trees</a><ul>
<li class="chapter" data-level="14.1.1" data-path="tree-based-models.html"><a href="tree-based-models.html#advantages-and-disadvantages-2"><i class="fa fa-check"></i><b>14.1.1</b> Advantages and disadvantages</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="tree-based-models.html"><a href="tree-based-models.html#ensemble-learning"><i class="fa fa-check"></i><b>14.2</b> Ensemble learning</a><ul>
<li class="chapter" data-level="14.2.1" data-path="tree-based-models.html"><a href="tree-based-models.html#bagging"><i class="fa fa-check"></i><b>14.2.1</b> Bagging</a></li>
<li class="chapter" data-level="14.2.2" data-path="tree-based-models.html"><a href="tree-based-models.html#boosting"><i class="fa fa-check"></i><b>14.2.2</b> Boosting</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="tree-based-models.html"><a href="tree-based-models.html#random-forests"><i class="fa fa-check"></i><b>14.3</b> Random Forests</a><ul>
<li class="chapter" data-level="14.3.1" data-path="tree-based-models.html"><a href="tree-based-models.html#example-3"><i class="fa fa-check"></i><b>14.3.1</b> Example</a></li>
<li class="chapter" data-level="14.3.2" data-path="tree-based-models.html"><a href="tree-based-models.html#variable-importance"><i class="fa fa-check"></i><b>14.3.2</b> Variable Importance</a></li>
<li class="chapter" data-level="14.3.3" data-path="tree-based-models.html"><a href="tree-based-models.html#partial-dependence"><i class="fa fa-check"></i><b>14.3.3</b> Partial dependence</a></li>
<li class="chapter" data-level="14.3.4" data-path="tree-based-models.html"><a href="tree-based-models.html#advantages-and-disadvantages-3"><i class="fa fa-check"></i><b>14.3.4</b> Advantages and disadvantages</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="tree-based-models.html"><a href="tree-based-models.html#gradient-boosted-trees"><i class="fa fa-check"></i><b>14.4</b> Gradient Boosted Trees</a><ul>
<li class="chapter" data-level="14.4.1" data-path="tree-based-models.html"><a href="tree-based-models.html#adaboost"><i class="fa fa-check"></i><b>14.4.1</b> AdaBoost</a></li>
<li class="chapter" data-level="14.4.2" data-path="tree-based-models.html"><a href="tree-based-models.html#gradient-boosting"><i class="fa fa-check"></i><b>14.4.2</b> Gradient Boosting</a></li>
<li class="chapter" data-level="14.4.3" data-path="tree-based-models.html"><a href="tree-based-models.html#notation"><i class="fa fa-check"></i><b>14.4.3</b> Notation</a></li>
<li class="chapter" data-level="14.4.4" data-path="tree-based-models.html"><a href="tree-based-models.html#parameters"><i class="fa fa-check"></i><b>14.4.4</b> Parameters</a></li>
<li class="chapter" data-level="14.4.5" data-path="tree-based-models.html"><a href="tree-based-models.html#example-4"><i class="fa fa-check"></i><b>14.4.5</b> Example</a></li>
<li class="chapter" data-level="14.4.6" data-path="tree-based-models.html"><a href="tree-based-models.html#advantages-and-disadvantages-4"><i class="fa fa-check"></i><b>14.4.6</b> Advantages and disadvantages</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="tree-based-models.html"><a href="tree-based-models.html#exercises-1"><i class="fa fa-check"></i><b>14.5</b> Exercises</a><ul>
<li class="chapter" data-level="14.5.1" data-path="tree-based-models.html"><a href="tree-based-models.html#rf-with-randomforest"><i class="fa fa-check"></i><b>14.5.1</b> 1. RF with <code>randomForest</code></a></li>
<li class="chapter" data-level="14.5.2" data-path="tree-based-models.html"><a href="tree-based-models.html#rf-tuning-with-caret"><i class="fa fa-check"></i><b>14.5.2</b> 2. RF tuning with <code>caret</code></a></li>
<li class="chapter" data-level="14.5.3" data-path="tree-based-models.html"><a href="tree-based-models.html#tuning-a-gbm-with-caret"><i class="fa fa-check"></i><b>14.5.3</b> 3. Tuning a GBM with <code>caret</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html"><i class="fa fa-check"></i><b>15</b> Unsupervised Learning</a><ul>
<li class="chapter" data-level="15.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#principal-component-analysis-pca"><i class="fa fa-check"></i><b>15.1</b> Principal Component Analysis (PCA)</a><ul>
<li class="chapter" data-level="15.1.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#example-pca-on-us-arrests"><i class="fa fa-check"></i><b>15.1.1</b> Example: PCA on US Arrests</a></li>
<li class="chapter" data-level="15.1.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#example-pca-on-cancel-cells"><i class="fa fa-check"></i><b>15.1.2</b> Example: PCA on Cancel Cells</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#clustering"><i class="fa fa-check"></i><b>15.2</b> Clustering</a><ul>
<li class="chapter" data-level="15.2.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#k-means-clustering"><i class="fa fa-check"></i><b>15.2.1</b> K-Means Clustering</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#hierarchical-clustering"><i class="fa fa-check"></i><b>15.3</b> Hierarchical Clustering</a><ul>
<li class="chapter" data-level="15.3.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#example-clustering-cancel-cells"><i class="fa fa-check"></i><b>15.3.1</b> Example: Clustering Cancel Cells</a></li>
<li class="chapter" data-level="15.3.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#references-1"><i class="fa fa-check"></i><b>15.3.2</b> References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="references-2.html"><a href="references-2.html"><i class="fa fa-check"></i><b>16</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Predictive Analytics for Actuaries</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-exploration" class="section level1">
<h1><span class="header-section-number"> 7</span> Data exploration</h1>
<p>Exploration is about making discoveries. You’ll need a strong sense of curiosity coupled with technical skill if you want to be able to make sense of the data. This chapter will give you the tools to take dirty, unprocessed data and clean it up, discover interesting trends using graphs and summary statistics, and communicate your results to a business audience.</p>
<p>About 10 - 15% of your grade will be based on data exploration. Every version of Exam PA such as December 2018, June 2019, and December 2019 have all had questions about data exploration. Putting in extra practice in this area is garanteed to give you a better score because it will free up time that you can use elsewhere.</p>
<p>Exploratory Data Analysis (EDA) is usually the first phase of an analytics project. This is as much of an art as it is a science because everyone has their own style. If you ask two actuaries perform EDA on the same data set, they will likely use different methods. These can be broken down into phases.</p>
<div class="figure"><span id="fig:unnamed-chunk-47"></span>
<img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-47-1.png" alt="Data Exploration Phases - From *R for Data Science*" width="700" />
<p class="caption">
Figure 7.1: Data Exploration Phases - From <em>R for Data Science</em>
</p>
</div>
<p>From the language on the December 2020 Syllabus, these are</p>
<p><strong>Import:</strong></p>
<ul>
<li>Evaluate the quality of appropriate data sources for a problem.</li>
<li>Identify the regulations, standards, and ethics surrounding predictive modeling and data</li>
</ul>
<p><strong>Tidy:</strong></p>
<ul>
<li>Identify structured, unstructured, and semi-structured data.</li>
<li>Identify the types of variables and terminology used in predictive modeling.</li>
<li>Understand basic methods of handling missing data.</li>
<li>Implement effective data design with respect to time frame, sampling, and granularity.</li>
</ul>
<p><strong>Transform:</strong></p>
<ul>
<li>Identify opportunities to create features from the basic data that may add value.</li>
<li>Identify outliers and other data issues.</li>
<li>Handle non-linear relationships via transformations.</li>
</ul>
<p><strong>Visualize:</strong></p>
<ul>
<li>Apply univariate and bivariate data exploration techniques.</li>
<li>Understand the key principles of constructing graphs.</li>
<li>Create a variety of graphs using the ggplot2 package.</li>
</ul>
<p><strong>Model:</strong></p>
<ul>
<li>Fit and interpret models</li>
</ul>
<p><strong>Communicate:</strong></p>
<ul>
<li>Write the report</li>
</ul>
<div id="how-to-make-graphs-in-r" class="section level2">
<h2><span class="header-section-number">7.1</span> How to make graphs in R</h2>
<p>Let’s create a histogram of the claims. The first step is to create a blank canvas that holds the columns that are needed. The library to make this is called <a href="https://ggplot2.tidyverse.org/">ggplot2</a>.</p>
<p>The <code>aesthetic</code> argument, <code>aes</code>, means that the variable shown will the the claims.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb131-1" title="1"><span class="kw">library</span>(ExamPAData)</a>
<a class="sourceLine" id="cb131-2" title="2">p &lt;-<span class="st"> </span>insurance <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(claims))</a></code></pre></div>
<p>If we look at <code>p</code>, we see that it is nothing but white space with axis for <code>count</code> and <code>income</code>.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" title="1">p</a></code></pre></div>
<p><img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-50-1.png" width="576" /></p>
<div id="add-a-plot" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Add a plot</h3>
<p>We add a histogram</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb133-1" title="1">p <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<p><img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-51-1.png" width="576" /></p>
<p>Different plots are called “geoms” for “geometric objects”. Geometry = Geo (space) + meter (measure), and graphs measure data. For instance, instead of creating a histogram, we can draw a gamma distribution with <code>stat_density</code>.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" title="1">p <span class="op">+</span><span class="st"> </span><span class="kw">stat_density</span>()</a></code></pre></div>
<p><img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-52-1.png" width="576" /></p>
<p>Create an xy plot by adding and <code>x</code> and a <code>y</code> argument to <code>aesthetic</code>.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" title="1">insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb135-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> holders, <span class="dt">y =</span> claims)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb135-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-53-1.png" width="576" /></p>
</div>
<div id="data-manipulation-chaining" class="section level3">
<h3><span class="header-section-number">7.1.2</span> Data manipulation chaining</h3>
<p>Pipes allow for data manipulations to be chained with visualizations.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" title="1">termlife <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb136-2" title="2"><span class="st">  </span><span class="kw">filter</span>(FACE <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb136-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">INCOME_AGE_RATIO =</span> INCOME<span class="op">/</span>AGE) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb136-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(INCOME_AGE_RATIO, FACE)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb136-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb136-6" title="6"><span class="st">  </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-54-1.png" width="576" /></p>
</div>
</div>
<div id="the-different-graph-types" class="section level2">
<h2><span class="header-section-number">7.2</span> The different graph types</h2>
<p>Only four types of graphs are used for data exploration. You will only need to understand how to interpret them. The SOA will provide you with code needed to create them. There will not be enough time for you to make your own graphs.</p>
<div id="histogram" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Histogram</h3>
<p>The <a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">histogram</a> is used when you want to look at the probability distribution of a continuous variable.</p>
<p>The template code in your Rmd file will look like this. Just change “variable” to the name without quotes of the variable and then copy and paste.</p>
</div>
<div id="box-plot" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Box plot</h3>
<p>The <a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">boxplot</a> compactly displays the distribution of a continuous variable. It visualises five summary statistics (the median, two hinges and two whiskers), and all “outlying” points individually.</p>
</div>
<div id="scatterplot" class="section level3">
<h3><span class="header-section-number">7.2.3</span> Scatterplot</h3>
<p>The <a href="https://ggplot2.tidyverse.org/reference/geom_point.html">point geom</a> is used to create scatterplots. The scatterplot is most useful for displaying the relationship between two continuous variables. It can be used to compare one continuous and one categorical variable, or two categorical variables.</p>
</div>
<div id="bar-charts" class="section level3">
<h3><span class="header-section-number">7.2.4</span> Bar charts</h3>
<p>There are two types of <a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">bar charts</a>: geom_bar() (Univariate) and geom_col() (Bivatiate). geom_bar() makes the height of the bar proportional to the number of cases in each group (or if the weight aesthetic is supplied, the sum of the weights). If you want the heights of the bars to represent values in the data, use geom_col() instead. geom_bar() uses stat_count() by default: it counts the number of cases at each x position.</p>
</div>
</div>
<div id="how-to-save-time-with-dplyr" class="section level2">
<h2><span class="header-section-number">7.3</span> How to save time with dplyr</h2>
<p>You may have noticed that writing code for data manipulation can be slow. Fortunately, there is a faster, 100%-legal, way of doing data manipulation that has worked for hundreds of exam candidates (the author included) who have taken Exam PA.</p>
<p>Up to this point we have been using old R libraries. By making use of newer R libraries we can save ourselves time. These will all be provided for you at Prometric within the <a href="https://www.tidyverse.org/">tidyverse</a> library.</p>
<p>Suggested reading of <em>R for Data Science</em> (<a href="https://r4ds.had.co.nz/index.html" class="uri">https://r4ds.had.co.nz/index.html</a>):</p>
<table>
<thead>
<tr class="header">
<th>Chapter</th>
<th>Topic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9</td>
<td>Introduction</td>
</tr>
<tr class="even">
<td>10</td>
<td>Tibbles</td>
</tr>
<tr class="odd">
<td>12</td>
<td>Tidy data</td>
</tr>
<tr class="even">
<td>15</td>
<td>Factors</td>
</tr>
<tr class="odd">
<td>17</td>
<td>Introduction</td>
</tr>
<tr class="even">
<td>18</td>
<td>Pipes</td>
</tr>
<tr class="odd">
<td>19</td>
<td>Functions</td>
</tr>
<tr class="even">
<td>20</td>
<td>Vectors</td>
</tr>
</tbody>
</table>
</div>
<div id="how-to-explore-the-data" class="section level2">
<h2><span class="header-section-number">7.4</span> How to explore the data</h2>
<p>Let’s look at the health insurance data set. This contains information on patients along with their annual health care costs.</p>
<p>The descriptions of the columns are below.</p>
<ul>
<li><code>age</code>: Age of the individual</li>
<li><code>sex</code>: Sex</li>
<li><code>bmi</code>: Body Mass Index</li>
<li><code>children</code>: Number of children</li>
<li><code>smoker</code>: Is this person a smoker?</li>
<li><code>region</code>: Region</li>
<li><code>charges</code>: Annual health care costs.</li>
</ul>
<p><code>head()</code> shows the top n rows. <code>head(20)</code> shows the top 20 rows.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" title="1"><span class="kw">head</span>(health_insurance)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 7
##     age sex      bmi children smoker region    charges
##   &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;       &lt;dbl&gt;
## 1    19 female  27.9        0 yes    southwest  16885.
## 2    18 male    33.8        1 no     southeast   1726.
## 3    28 male    33          3 no     southeast   4449.
## 4    33 male    22.7        0 no     northwest  21984.
## 5    32 male    28.9        0 no     northwest   3867.
## 6    31 female  25.7        0 no     southeast   3757.</code></pre>
<p>Using a pipe is an alternative way of doing this.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</a></code></pre></div>
<p></br></p>
<div class="studytip">
<p>
<strong>Shortcut:</strong> Use <code>CTRL</code> + <code>SHFT</code> + <code>M</code> to create pipes <code>%&gt;%</code>
</p>
</div>
<p></br></p>
<p>The <code>glimpse</code> function is similar to <code>str()</code>.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">glimpse</span>()</a></code></pre></div>
<pre><code>## Observations: 1,338
## Variables: 7
## $ age      &lt;dbl&gt; 19, 18, 28, 33, 32, 31, 46, 37, 37, 60, 25, 62, 23, 56, 27...
## $ sex      &lt;chr&gt; &quot;female&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;female&quot;, &quot;femal...
## $ bmi      &lt;dbl&gt; 27.900, 33.770, 33.000, 22.705, 28.880, 25.740, 33.440, 27...
## $ children &lt;dbl&gt; 0, 1, 3, 0, 0, 0, 1, 3, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0...
## $ smoker   &lt;chr&gt; &quot;yes&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no...
## $ region   &lt;chr&gt; &quot;southwest&quot;, &quot;southeast&quot;, &quot;southeast&quot;, &quot;northwest&quot;, &quot;north...
## $ charges  &lt;dbl&gt; 16884.924, 1725.552, 4449.462, 21984.471, 3866.855, 3756.6...</code></pre>
<p>One of the most useful data science tools is counting things. The function <code>count()</code> gives the number of records by a categorical feature.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span>dplyr<span class="op">::</span><span class="kw">count</span>(children)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   children     n
##      &lt;dbl&gt; &lt;int&gt;
## 1        0   574
## 2        1   324
## 3        2   240
## 4        3   157
## 5        4    25
## 6        5    18</code></pre>
<p>Two categories can be counted at once. This creates a table with all combinations of <code>region</code> and <code>sex</code> and shows the number of records in each category.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(region, sex)</a></code></pre></div>
<pre><code>## # A tibble: 8 x 3
##   region    sex        n
##   &lt;chr&gt;     &lt;chr&gt;  &lt;int&gt;
## 1 northeast female   161
## 2 northeast male     163
## 3 northwest female   164
## 4 northwest male     161
## 5 southeast female   175
## 6 southeast male     189
## 7 southwest female   162
## 8 southwest male     163</code></pre>
<p>The <code>summary()</code> function is shows a statistical summary. One caveat is that each column needs to be in it’s appropriate type. For example, <code>smoker</code>, <code>region</code>, and <code>sex</code> are all listed as characters when if they were factors, <code>summary</code> would give you count info.</p>
<p><strong>With incorrect data types</strong></p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##       age            sex                 bmi           children    
##  Min.   :18.00   Length:1338        Min.   :15.96   Min.   :0.000  
##  1st Qu.:27.00   Class :character   1st Qu.:26.30   1st Qu.:0.000  
##  Median :39.00   Mode  :character   Median :30.40   Median :1.000  
##  Mean   :39.21                      Mean   :30.66   Mean   :1.095  
##  3rd Qu.:51.00                      3rd Qu.:34.69   3rd Qu.:2.000  
##  Max.   :64.00                      Max.   :53.13   Max.   :5.000  
##     smoker             region             charges     
##  Length:1338        Length:1338        Min.   : 1122  
##  Class :character   Class :character   1st Qu.: 4740  
##  Mode  :character   Mode  :character   Median : 9382  
##                                        Mean   :13270  
##                                        3rd Qu.:16640  
##                                        Max.   :63770</code></pre>
<p><strong>With correct data types</strong></p>
<p>This tells you that there are 324 patients in the northeast, 325 in the northwest, 364 in the southeast, and so fourth.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" title="1">health_insurance &lt;-<span class="st"> </span>health_insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb148-2" title="2"><span class="st">  </span><span class="kw">mutate_if</span>(is.character, as.factor)</a>
<a class="sourceLine" id="cb148-3" title="3"></a>
<a class="sourceLine" id="cb148-4" title="4">health_insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb148-5" title="5"><span class="st">  </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##       age            sex           bmi           children     smoker    
##  Min.   :18.00   female:662   Min.   :15.96   Min.   :0.000   no :1064  
##  1st Qu.:27.00   male  :676   1st Qu.:26.30   1st Qu.:0.000   yes: 274  
##  Median :39.00                Median :30.40   Median :1.000             
##  Mean   :39.21                Mean   :30.66   Mean   :1.095             
##  3rd Qu.:51.00                3rd Qu.:34.69   3rd Qu.:2.000             
##  Max.   :64.00                Max.   :53.13   Max.   :5.000             
##        region       charges     
##  northeast:324   Min.   : 1122  
##  northwest:325   1st Qu.: 4740  
##  southeast:364   Median : 9382  
##  southwest:325   Mean   :13270  
##                  3rd Qu.:16640  
##                  Max.   :63770</code></pre>
<div class="studytip">
<p>
<strong>Shortcut:</strong> This “mutate_if” trick can save you time from having to copy and paste from the SOA’s template code and convert each variable to a factor individually
</p>
</div>
</div>
<div id="how-to-transform-the-data" class="section level2">
<h2><span class="header-section-number">7.5</span> How to transform the data</h2>
<p>Transforming, manipulating, querying, and wrangling are synonyms in data terminology.</p>
<p>R syntax is designed to be similar to SQL. They begin with a <code>SELECT</code>, use <code>GROUP BY</code> to aggregate, and have a <code>WHERE</code> to remove records. Unlike SQL, the ordering of these does not matter. <code>SELECT</code> can come after a <code>WHERE</code>.</p>
<p><strong>R to SQL translation</strong></p>
<pre><code>select() -&gt; SELECT
mutate() -&gt; user-defined columns
summarize() -&gt; aggregated columns
left_join() -&gt; LEFT JOIN
filter() -&gt; WHERE
group_by() -&gt; GROUP BY
filter() -&gt; HAVING
arrange() -&gt; ORDER BY
</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb151-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb151-2" title="2"><span class="st">  </span><span class="kw">select</span>(age, region) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb151-3" title="3"><span class="st">  </span><span class="kw">head</span>()</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##     age region   
##   &lt;dbl&gt; &lt;fct&gt;    
## 1    19 southwest
## 2    18 southeast
## 3    28 southeast
## 4    33 northwest
## 5    32 northwest
## 6    31 southeast</code></pre>
<p>Let’s look at only those in the southeast region. Instead of <code>WHERE</code>, use <code>filter</code>.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb153-2" title="2"><span class="st">  </span><span class="kw">filter</span>(region <span class="op">==</span><span class="st"> &quot;southeast&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb153-3" title="3"><span class="st">  </span><span class="kw">select</span>(age, region) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb153-4" title="4"><span class="st">  </span><span class="kw">head</span>()</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##     age region   
##   &lt;dbl&gt; &lt;fct&gt;    
## 1    18 southeast
## 2    28 southeast
## 3    31 southeast
## 4    46 southeast
## 5    62 southeast
## 6    56 southeast</code></pre>
<p>The SQL translation is</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode sql"><code class="sourceCode sql"><a class="sourceLine" id="cb155-1" title="1"><span class="kw">SELECT</span> age, region</a>
<a class="sourceLine" id="cb155-2" title="2"><span class="kw">FROM</span> health_insurance</a>
<a class="sourceLine" id="cb155-3" title="3"><span class="kw">WHERE</span> region <span class="op">=</span> <span class="st">&#39;southeast&#39;</span></a></code></pre></div>
<p>Instead of <code>ORDER BY</code>, use <code>arrange</code>. Unlike SQL, the order does not matter and <code>ORDER BY</code> doesn’t need to be last.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb156-2" title="2"><span class="st">  </span><span class="kw">arrange</span>(age) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb156-3" title="3"><span class="st">  </span><span class="kw">select</span>(age, region) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb156-4" title="4"><span class="st">  </span><span class="kw">head</span>()</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##     age region   
##   &lt;dbl&gt; &lt;fct&gt;    
## 1    18 southeast
## 2    18 southeast
## 3    18 northeast
## 4    18 northeast
## 5    18 northeast
## 6    18 southeast</code></pre>
<p>The <code>group_by</code> comes before the aggregation, unlike in SQL where the <code>GROUP BY</code> comes last.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb158-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(region) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb158-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg_age =</span> <span class="kw">mean</span>(age))</a></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   region    avg_age
##   &lt;fct&gt;       &lt;dbl&gt;
## 1 northeast    39.3
## 2 northwest    39.2
## 3 southeast    38.9
## 4 southwest    39.5</code></pre>
<p>In SQL, this would be</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode sql"><code class="sourceCode sql"><a class="sourceLine" id="cb160-1" title="1"><span class="kw">SELECT</span> region, </a>
<a class="sourceLine" id="cb160-2" title="2">       <span class="fu">AVG</span>(age) <span class="kw">as</span> avg_age</a>
<a class="sourceLine" id="cb160-3" title="3"><span class="kw">FROM</span> health_insurance</a>
<a class="sourceLine" id="cb160-4" title="4"><span class="kw">GROUP</span> <span class="kw">BY</span> region</a></code></pre></div>
<p>Just like in SQL, many different aggregate functions can be used such as <code>SUM</code>, <code>MEAN</code>, <code>MIN</code>, <code>MAX</code>, and so forth.</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb161-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(region) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb161-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg_age =</span> <span class="kw">mean</span>(age),</a>
<a class="sourceLine" id="cb161-4" title="4">            <span class="dt">max_age =</span> <span class="kw">max</span>(age),</a>
<a class="sourceLine" id="cb161-5" title="5">            <span class="dt">median_charges =</span> <span class="kw">median</span>(charges),</a>
<a class="sourceLine" id="cb161-6" title="6">            <span class="dt">bmi_std_dev =</span> <span class="kw">sd</span>(bmi))</a></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   region    avg_age max_age median_charges bmi_std_dev
##   &lt;fct&gt;       &lt;dbl&gt;   &lt;dbl&gt;          &lt;dbl&gt;       &lt;dbl&gt;
## 1 northeast    39.3      64         10058.        5.94
## 2 northwest    39.2      64          8966.        5.14
## 3 southeast    38.9      64          9294.        6.48
## 4 southwest    39.5      64          8799.        5.69</code></pre>
<p>To create new columns, the <code>mutate</code> function is used. For example, if we wanted a column of the person’s annual charges divided by their age</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb163-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">charges_over_age =</span> charges<span class="op">/</span>age) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb163-3" title="3"><span class="st">  </span><span class="kw">select</span>(age, charges, charges_over_age) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb163-4" title="4"><span class="st">  </span><span class="kw">head</span>(<span class="dv">5</span>)</a></code></pre></div>
<pre><code>## # A tibble: 5 x 3
##     age charges charges_over_age
##   &lt;dbl&gt;   &lt;dbl&gt;            &lt;dbl&gt;
## 1    19  16885.            889. 
## 2    18   1726.             95.9
## 3    28   4449.            159. 
## 4    33  21984.            666. 
## 5    32   3867.            121.</code></pre>
<p>We can create as many new columns as we want.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb165-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_squared  =</span> age<span class="op">^</span><span class="dv">2</span>,</a>
<a class="sourceLine" id="cb165-3" title="3">         <span class="dt">age_cubed =</span> age<span class="op">^</span><span class="dv">3</span>,</a>
<a class="sourceLine" id="cb165-4" title="4">         <span class="dt">age_fourth =</span> age<span class="op">^</span><span class="dv">4</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb165-5" title="5"><span class="st">  </span><span class="kw">head</span>(<span class="dv">5</span>)</a></code></pre></div>
<pre><code>## # A tibble: 5 x 10
##     age sex     bmi children smoker region charges age_squared age_cubed
##   &lt;dbl&gt; &lt;fct&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt;    &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;
## 1    19 fema~  27.9        0 yes    south~  16885.         361      6859
## 2    18 male   33.8        1 no     south~   1726.         324      5832
## 3    28 male   33          3 no     south~   4449.         784     21952
## 4    33 male   22.7        0 no     north~  21984.        1089     35937
## 5    32 male   28.9        0 no     north~   3867.        1024     32768
## # ... with 1 more variable: age_fourth &lt;dbl&gt;</code></pre>
<p>The <code>CASE WHEN</code> function is quite similar to SQL. For example, we can create a column which is <code>0</code> when <code>age &lt; 50</code>, <code>1</code> when <code>50 &lt;= age &lt;= 70</code>, and <code>2</code> when <code>age &gt; 70</code>.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" title="1">health_insurance <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb167-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_bucket =</span> <span class="kw">case_when</span>(age <span class="op">&lt;</span><span class="st"> </span><span class="dv">50</span> <span class="op">~</span><span class="st"> </span><span class="dv">0</span>,</a>
<a class="sourceLine" id="cb167-3" title="3">                                age <span class="op">&lt;=</span><span class="st"> </span><span class="dv">70</span> <span class="op">~</span><span class="st"> </span><span class="dv">1</span>,</a>
<a class="sourceLine" id="cb167-4" title="4">                                age <span class="op">&gt;</span><span class="st"> </span><span class="dv">70</span> <span class="op">~</span><span class="st"> </span><span class="dv">2</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb167-5" title="5"><span class="st">  </span><span class="kw">select</span>(age, age_bucket)</a></code></pre></div>
<pre><code>## # A tibble: 1,338 x 2
##      age age_bucket
##    &lt;dbl&gt;      &lt;dbl&gt;
##  1    19          0
##  2    18          0
##  3    28          0
##  4    33          0
##  5    32          0
##  6    31          0
##  7    46          0
##  8    37          0
##  9    37          0
## 10    60          1
## # ... with 1,328 more rows</code></pre>
<p>SQL translation:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode sql"><code class="sourceCode sql"><a class="sourceLine" id="cb169-1" title="1"><span class="kw">SELECT</span> <span class="cf">CASE</span> <span class="cf">WHEN</span> AGE <span class="op">&lt;</span> <span class="dv">50</span> <span class="cf">THEN</span> <span class="dv">0</span></a>
<a class="sourceLine" id="cb169-2" title="2">       <span class="cf">ELSE</span> <span class="cf">WHEN</span> AGE <span class="op">&lt;=</span> <span class="dv">70</span> <span class="cf">THEN</span> <span class="dv">1</span></a>
<a class="sourceLine" id="cb169-3" title="3">       <span class="cf">ELSE</span> <span class="dv">2</span></a>
<a class="sourceLine" id="cb169-4" title="4"><span class="kw">FROM</span> health_insurance</a></code></pre></div>
</div>
<div id="a-real-example" class="section level2">
<h2><span class="header-section-number">7.6</span> A real example</h2>
<p>This chapter is based on the first task of the December 2019 Exam PA.</p>
<p><strong>TASK 1 (12 points)</strong></p>
<blockquote>
<p>Examine each variable and make appropriate adjustments.</p>
</blockquote>
<blockquote>
<p>Examine each predictor variable other than cap_gain both on its own and with respect to value_flag. Make appropriate adjustments. Do not make any adjustments to the cap_gain variable at this time.</p>
</blockquote>
<blockquote>
<p>There should be no further variable adjustments unless specifically requested.</p>
</blockquote>
<p>As a reminder, all data for this book can be accessed from the package <code>ExamPAData</code>. In the real exam, you will read the file from the Prometric computer.</p>
<p>Because the data is already loaded, simply use the below code to access the data.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" title="1"><span class="kw">library</span>(ExamPAData)</a></code></pre></div>
<p>To save keystrokes, give the data a short name such as <code>df</code> for “data frame”.</p>
<div id="garbage-in-garbage-out" class="section level3">
<h3><span class="header-section-number">7.6.1</span> Garbage in; garbage out 🗑</h3>
<p>This is a common saying when working with predictive models. No matter how complex the model, if the data is bad then the entire result will be bad. For this exam, master the art of data manipulation and everything becomes easier!</p>
<p>Begin by looking at a summary.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" title="1"><span class="kw">summary</span>(df)</a></code></pre></div>
<pre><code>##       age        education_num                 marital_status     occupation   
##  Min.   :17.00   Min.   : 1.00   Divorced             : 6633   Group 1 : 7237  
##  1st Qu.:28.00   1st Qu.: 9.00   Married-AF-spouse    :   37   Group 2 :10123  
##  Median :37.00   Median :10.00   Married-civ-spouse   :22379   Group 3 :13971  
##  Mean   :38.64   Mean   :10.08   Married-spouse-absent:  628   Group 4 : 2444  
##  3rd Qu.:48.00   3rd Qu.:12.00   Never-married        :16117   Group 5 :12258  
##  Max.   :90.00   Max.   :16.00   Separated            : 1530   Group NA: 2809  
##                                  Widowed              : 1518                   
##     cap_gain     hours_per_week      score       value_flag  
##  Min.   :    0   Min.   : 1.00   Min.   :43.94   High:11687  
##  1st Qu.:    0   1st Qu.:40.00   1st Qu.:57.50   Low :37155  
##  Median :    0   Median :40.00   Median :60.24               
##  Mean   : 1079   Mean   :40.42   Mean   :60.23               
##  3rd Qu.:    0   3rd Qu.:45.00   3rd Qu.:62.95               
##  Max.   :99999   Max.   :99.00   Max.   :76.53               
## </code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" title="1"><span class="kw">str</span>(df)</a></code></pre></div>
<pre><code>## Classes &#39;spec_tbl_df&#39;, &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;: 48842 obs. of  8 variables:
##  $ age           : num  39 50 38 53 28 37 49 52 31 42 ...
##  $ education_num : num  13 13 9 7 13 14 5 9 14 13 ...
##  $ marital_status: Factor w/ 7 levels &quot;Divorced&quot;,&quot;Married-AF-spouse&quot;,..: 5 3 1 3 3 3 4 3 5 3 ...
##  $ occupation    : Factor w/ 6 levels &quot;Group 1&quot;,&quot;Group 2&quot;,..: 2 5 1 1 5 5 1 5 5 5 ...
##  $ cap_gain      : num  2174 0 0 0 0 ...
##  $ hours_per_week: num  40 13 40 40 40 40 16 45 50 40 ...
##  $ score         : num  59 55.8 62.8 60.1 53.3 ...
##  $ value_flag    : Factor w/ 2 levels &quot;High&quot;,&quot;Low&quot;: 2 2 2 2 2 2 2 1 1 1 ...</code></pre>
</div>
<div id="be-a-detective" class="section level3">
<h3><span class="header-section-number">7.6.2</span> Be a detective 🔎</h3>
<p>Sherlock Holmes is famous for saying “You see, Watson, but you do not observe!”</p>
<p>Just like detectives, actuaries need to collect data and make observations. Each exam has a few “anomalies” in the data which they expect candidates to mention. These could be</p>
<ul>
<li>Any value that doesn’t match the Data Dictionary in the Project Statement</li>
<li>Variables that have <code>NA</code> values</li>
<li>Variables that have a lot of factor levels</li>
<li>Incorrect data types
<ul>
<li>Factors that are read as characters or vice versa</li>
<li>Numeric variables that are factor/character</li>
</ul></li>
<li>Extreme values (Numeric values are too high or low)</li>
</ul>
<p>You’ll get very good at spotting these with practice. Just from looking at the above <code>summary</code>, we can observe the following:</p>
<p><strong>Observations</strong></p>
<ul>
<li>The data consists of 48,842 obs. of 8 variables.</li>
<li>The lowest <code>age</code> is 17 but the Project Statement says to only include records with <code>age</code> &gt;= 25.</li>
<li>The <code>cap_gain</code> distribution is right skewed because the median (0) is less than the mean (1079) but the Project Statement said not to transform this. Otherwise I would apply a log transform.</li>
<li><code>education_num</code> takes integer values between 1 and 16. There are a lot of values that are low.</li>
<li>There are missing values when <code>occupation</code> is <code>group NA</code>, which means that the person’s occupation is unknown.</li>
<li>The amount that people work per work, <code>hours_per_week</code>, varies by a lot. The lowest is 1 hour and the highest is 99. Most people work 40 hours per week.</li>
</ul>
<div class="studytip">
<p>
<strong>Study Tip:</strong> Never apply a log transform to the target variable. Only the predictor variables get logs taken. At this stage we simply note if it is right-skewed or not.
</p>
</div>
<p>The SOA’s solution recommends leaving comments in your Rmd file. This helps to give you partial credit on questions that you may answer incorrectly.</p>
<p><strong>Good comments</strong></p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" title="1"><span class="co">#I observe that there are no missing values other than those indicated by Group NA for occupation.</span></a>
<a class="sourceLine" id="cb175-2" title="2"></a>
<a class="sourceLine" id="cb175-3" title="3"><span class="co">#I removed the code provided by my assistant. It is embedded in later chunks as needed.</span></a>
<a class="sourceLine" id="cb175-4" title="4"></a>
<a class="sourceLine" id="cb175-5" title="5"><span class="co">#I excluded people under the age of 25</span></a>
<a class="sourceLine" id="cb175-6" title="6">df &lt;-<span class="st"> </span>df[df<span class="op">$</span>age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">25</span>,]</a>
<a class="sourceLine" id="cb175-7" title="7"></a>
<a class="sourceLine" id="cb175-8" title="8"><span class="co">#I convert the target to 0-1.</span></a>
<a class="sourceLine" id="cb175-9" title="9">df<span class="op">$</span>value_flag &lt;-<span class="st"> </span><span class="kw">ifelse</span>(df<span class="op">$</span>value_flag <span class="op">==</span><span class="st"> &quot;High&quot;</span>,<span class="dv">1</span>,<span class="dv">0</span>)</a></code></pre></div>
<p><strong>Useless comments</strong></p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb176-1" title="1"><span class="co">#this is a comment</span></a>
<a class="sourceLine" id="cb176-2" title="2"></a>
<a class="sourceLine" id="cb176-3" title="3"><span class="co">#this loads a library called ggplot2</span></a>
<a class="sourceLine" id="cb176-4" title="4"><span class="kw">library</span>(ggplot2)</a></code></pre></div>
</div>
<div id="a-picture-is-worth-a-thousand-words" class="section level3">
<h3><span class="header-section-number">7.6.3</span> A picture is worth a thousand words 📷</h3>
<p>What’s your favorite type of graph? Mine is a radar chart This is a graphical method of displaying multivariate data in the form of a two-dimensional chart of three or more quantitative variables represented on axes staring from the same point.</p>
<p>Isn’t this pretty?</p>
<p><img src="images/radar_graph.png" width="1300%" style="display: block; margin: auto;" /></p>
<p><strong>Don’t waste time trying to make the graphs perfect!</strong></p>
<p>Only change code that you <strong>need</strong> to change. The SOA is trying to help you save time by giving you templates. That being said, if you can do it faster on your own, then do it your own way.</p>
<p>This is the code template that they give you. You only need to change the “variable” names.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" title="1"><span class="co"># This code makes a histogram for a continuous variable.</span></a>
<a class="sourceLine" id="cb177-2" title="2"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> variable)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb177-3" title="3"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb177-4" title="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;variable&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb177-5" title="5"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>))</a>
<a class="sourceLine" id="cb177-6" title="6"></a>
<a class="sourceLine" id="cb177-7" title="7"><span class="co"># This code makes a bar chart for a factor variable.</span></a>
<a class="sourceLine" id="cb177-8" title="8"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> variable)) <span class="op">+</span></a>
<a class="sourceLine" id="cb177-9" title="9"><span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb177-10" title="10"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;variable&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb177-11" title="11"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>))</a></code></pre></div>
<p>Okay, that wasn’t 100% true. It’s common for the code to require <strong>small</strong> changes. For instance, the histogram that they give you has bins that are too narrow for<code>age</code>, which causes these spikes to show up in the graph.</p>
<blockquote>
<p>The best candidates altered the code to create more appropriate plots and summary tables.</p>
</blockquote>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" title="1"><span class="co"># This code makes a histogram for a continuous variable.</span></a>
<a class="sourceLine" id="cb178-2" title="2"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> age)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb178-3" title="3"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>) <span class="op">+</span><span class="st"> </span><span class="co">#not the right number of bins</span></a>
<a class="sourceLine" id="cb178-4" title="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;age&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb178-5" title="5"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb178-6" title="6"><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Bad: Default histogram with spikes&quot;</span>)</a></code></pre></div>
<p><img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-83-1.png" width="576" /></p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb179-1" title="1"><span class="co">#Histograms of continuous variables</span></a>
<a class="sourceLine" id="cb179-2" title="2"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> age)) <span class="op">+</span></a>
<a class="sourceLine" id="cb179-3" title="3"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="fl">24.5</span>,<span class="fl">99.5</span>, <span class="dt">by =</span> <span class="dv">5</span>)) <span class="op">+</span><span class="st">  </span><span class="co">#make bins wider and set range </span></a>
<a class="sourceLine" id="cb179-4" title="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb179-5" title="5"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb179-6" title="6"><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Good: After adjusting the breaks&quot;</span>)</a></code></pre></div>
<p><img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-83-2.png" width="576" /></p>
<p>How do you know when a variable should a factor and when it should be numeric?</p>
</div>
<div id="factor-or-numeric" class="section level3">
<h3><span class="header-section-number">7.6.4</span> Factor or numeric ❓</h3>
<p>Which variables should be converted to factors and which should be numeric?</p>
<p>Questions of this sort have come up twice. On Hospital Readmissions, there was a Length of Stay variable that was numeric, but had only a few values and so some candidates treated it as a factor. The <code>education_num</code> variable here is also numeric but only has 16 unique values. So should this be a numeric or a factor?</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>education_num)</a></code></pre></div>
<pre><code>## 
##     1     2     3     4     5     6     7     8     9    10    11    12    13 
##    68   231   446   877   618   995  1042   382 13320  7812  1862  1411  7298 
##    14    15    16 
##  2621   834   593</code></pre>
<p>Ask yourself this question: is there a way of comparing two values of the variable together?</p>
<ul>
<li>If yes, then use numeric<br />
</li>
<li>If no, then use a factor</li>
</ul>
<p>For exmaple, we can say that <code>education_num = 2</code> is less than <code>education_num = 4</code>, which means that there’s a natural order. This is also known as an <strong>ordinal</strong>.</p>
<p>If the factor is say, <code>color</code>, which can be <code>red</code>, <code>blue</code>, or <code>green</code>, then there is no way of comparing values together. Is <code>red</code> greater than <code>blue</code>? This question has no meaning.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" title="1"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> education_num)) <span class="op">+</span></a>
<a class="sourceLine" id="cb182-2" title="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb182-3" title="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Education&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb182-4" title="4"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb182-5" title="5"><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Default number of bins (30)&quot;</span>)</a></code></pre></div>
<p><img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-85-1.png" width="576" /></p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" title="1"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> education_num)) <span class="op">+</span></a>
<a class="sourceLine" id="cb183-2" title="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">16</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb183-3" title="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Education&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb183-4" title="4"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb183-5" title="5"><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Set number of bins to number of factor levels (16) &quot;</span>)</a></code></pre></div>
<p><img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-85-2.png" width="576" /></p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" title="1"><span class="co"># Set bins equal to number of levels, could have made bar chart.</span></a></code></pre></div>
<p>We could also use a bar plot.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" title="1"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> education_num)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb185-2" title="2"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;count&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb185-3" title="3"><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Bar plot&quot;</span>)</a></code></pre></div>
<p><img src="Exam-PA-Study-Manual_files/figure-html/unnamed-chunk-86-1.png" width="576" /></p>
<p>Lastly, read the Project Statement carefully and only do what it tells you to do.</p>
<blockquote>
<p>Candidates were not required to make a plot for cap_gain. This solution has the plot made here rather than in Task 6.</p>
</blockquote>
</div>
<div id="of-statistics-are-false" class="section level3">
<h3><span class="header-section-number">7.6.5</span> 73.6% of statistics are false 🤯</h3>
<p>Really? No, but statistics can help you see patterns that data visualization by itself can miss. Along with the ggplot codes, there will be code to look at summary statistics. Here’s a refresher on what these statistics mean (no pun intended).</p>
<ul>
<li><strong>Mean</strong>: The average. This gets skewed by outliers easily. If the mean is greater than the median, then the distribution is right skewed.</li>
<li><strong>Median</strong>: The “middle” value. This is an average that reduces the impact of outliers.</li>
<li><strong>Variance</strong>: The amount by which each observation differs from the mean.<br />
</li>
<li><strong>Standard Deviation</strong>: The square root of the variance.</li>
<li><strong>n()</strong>: The number of observations. Always take note of groups that don’t have many observations.</li>
</ul>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb186-1" title="1"><span class="co"># This code provides, for each level of a factor variable, the number for which value_flag is zero, the number for which it is one, the total number of observations, and the proportion of ones.</span></a>
<a class="sourceLine" id="cb186-2" title="2"><span class="co"># Note that the variable name should not be enclosed in quotation marks.</span></a>
<a class="sourceLine" id="cb186-3" title="3">df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb186-4" title="4"><span class="st">  </span><span class="kw">group_by</span>(variable) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb186-5" title="5"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb186-6" title="6">    <span class="dt">zeros =</span> <span class="kw">sum</span>(value_flag <span class="op">==</span><span class="st"> </span><span class="dv">0</span>),</a>
<a class="sourceLine" id="cb186-7" title="7">    <span class="dt">ones =</span> <span class="kw">sum</span>(value_flag <span class="op">==</span><span class="st"> </span><span class="dv">1</span>),</a>
<a class="sourceLine" id="cb186-8" title="8">    <span class="dt">n =</span> <span class="kw">n</span>(),</a>
<a class="sourceLine" id="cb186-9" title="9">    <span class="dt">proportion =</span> <span class="kw">mean</span>(value_flag)</a>
<a class="sourceLine" id="cb186-10" title="10">  )</a></code></pre></div>
<p>Factors levels should be simplified. If a group has only a few observations then there will be problems with the model. In our data, take a look at the <code>marital_status</code> column. Do you observe anything unusual?</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>marital_status)</a></code></pre></div>
<pre><code>## 
##              Divorced     Married-AF-spouse    Married-civ-spouse 
##                  6498                    31                 21661 
## Married-spouse-absent         Never-married             Separated 
##                   573                  8697                  1438 
##               Widowed 
##                  1512</code></pre>
<p>Only 31 records have <code>Married-AF-spouse</code>. This is because the sample size <code>n = 31</code> is too small. In modeling jargon, this is “statistical insignificant” and will cause the p-value on <code>marital_status</code> to be large. You can fix this in a few different ways</p>
<ul>
<li>Delete these records (Not recommended)</li>
<li>Group these records together with <code>Married-spouse</code> (Simplest method)</li>
</ul>
<p>Let’s use the second method.</p>
<p>First, look at the levels of the factor variable.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" title="1"><span class="kw">levels</span>(df<span class="op">$</span>marital_status)</a></code></pre></div>
<pre><code>## [1] &quot;Divorced&quot;              &quot;Married-AF-spouse&quot;     &quot;Married-civ-spouse&quot;   
## [4] &quot;Married-spouse-absent&quot; &quot;Never-married&quot;         &quot;Separated&quot;            
## [7] &quot;Widowed&quot;</code></pre>
<p>Now look at the profitability across marital status. For <code>Married-AF-spouse</code> and <code>Married-civ-spouse</code> the proportion of high profit customers is <strong>high</strong>, but for <code>Married-spouse-absent</code> it is <strong>low.</strong> Even though these are all “married”, it would be a bad idea to combine them because the profitability is so different.</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb191-1" title="1"><span class="co">#Proportion of ones by category of factor variable</span></a>
<a class="sourceLine" id="cb191-2" title="2">df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb191-3" title="3"><span class="st">  </span><span class="kw">group_by</span>(marital_status) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb191-4" title="4"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb191-5" title="5">    <span class="dt">zeros =</span> <span class="kw">sum</span>(value_flag <span class="op">==</span><span class="st"> </span><span class="dv">0</span>),</a>
<a class="sourceLine" id="cb191-6" title="6">    <span class="dt">ones =</span> <span class="kw">sum</span>(value_flag <span class="op">==</span><span class="st"> </span><span class="dv">1</span>),</a>
<a class="sourceLine" id="cb191-7" title="7">    <span class="dt">n =</span> <span class="kw">n</span>(),</a>
<a class="sourceLine" id="cb191-8" title="8">    <span class="dt">proportion =</span> <span class="kw">mean</span>(value_flag)</a>
<a class="sourceLine" id="cb191-9" title="9">  )</a></code></pre></div>
<pre><code>## # A tibble: 7 x 5
##   marital_status        zeros  ones     n proportion
##   &lt;fct&gt;                 &lt;int&gt; &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;
## 1 Divorced               5829   669  6498     0.103 
## 2 Married-AF-spouse        19    12    31     0.387 
## 3 Married-civ-spouse    11727  9934 21661     0.459 
## 4 Married-spouse-absent   515    58   573     0.101 
## 5 Never-married          8000   697  8697     0.0801
## 6 Separated              1342    96  1438     0.0668
## 7 Widowed                1384   128  1512     0.0847</code></pre>
<p>Then create a vector that has the simpler levels that you want. The order needs to be the same.</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" title="1">simple_levels &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Divorced&quot;</span>, <span class="st">&quot;Married-spouse&quot;</span>, <span class="st">&quot;Married-spouse&quot;</span>, <span class="st">&quot;Married-spuouse-absent&quot;</span>, <span class="st">&quot;Neber-married&quot;</span>, <span class="st">&quot;Separated&quot;</span>, <span class="st">&quot;Widowed&quot;</span>)</a></code></pre></div>
<p>The function <code>mapvalues</code> takes in three arguments. You can read about this by typing <code>?mapvalues</code> into the console.</p>
<p><code>x</code> : the factor or vector to modify</p>
<p><code>from</code> : a vector of the items to replace</p>
<p><code>to</code> : a vector of replacement values</p>
<p>Then map the old values to the simpler values.</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb194-1" title="1"><span class="co">#Combine the two marital status levels</span></a>
<a class="sourceLine" id="cb194-2" title="2">var.levels &lt;-<span class="st"> </span><span class="kw">levels</span>(df<span class="op">$</span>marital_status)</a>
<a class="sourceLine" id="cb194-3" title="3">df<span class="op">$</span>marital_status &lt;-<span class="st"> </span><span class="kw">mapvalues</span>(<span class="dt">x =</span> df<span class="op">$</span>marital_status,</a>
<a class="sourceLine" id="cb194-4" title="4">                               <span class="dt">from =</span> var.levels, </a>
<a class="sourceLine" id="cb194-5" title="5">                               <span class="dt">to =</span> simple_levels) </a></code></pre></div>
<p>Now, when you look at the <code>marital_status</code> levels, you will see the simpler levels.</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" title="1"><span class="kw">levels</span>(df<span class="op">$</span>marital_status)</a></code></pre></div>
<pre><code>## [1] &quot;Divorced&quot;               &quot;Married-spouse&quot;         &quot;Married-spuouse-absent&quot;
## [4] &quot;Neber-married&quot;          &quot;Separated&quot;              &quot;Widowed&quot;</code></pre>
<p>You can also check that the number of records is what you expect.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>marital_status)</a></code></pre></div>
<pre><code>## 
##               Divorced         Married-spouse Married-spuouse-absent 
##                   6498                  21692                    573 
##          Neber-married              Separated                Widowed 
##                   8697                   1438                   1512</code></pre>
</div>
</div>
<div id="exercises" class="section level2">
<h2><span class="header-section-number">7.7</span> Exercises</h2>
<p>Run this code on your computer to answer these exercises.</p>
<p>The data <code>actuary_salaries</code> contains the salaries of actuaries collected from the DW Simpson survey. Use this data to answer the exercises below.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" title="1">actuary_salaries <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">glimpse</span>()</a></code></pre></div>
<pre><code>## Observations: 138
## Variables: 6
## $ industry    &lt;chr&gt; &quot;Casualty&quot;, &quot;Casualty&quot;, &quot;Casualty&quot;, &quot;Casualty&quot;, &quot;Casual...
## $ exams       &lt;chr&gt; &quot;1 Exam&quot;, &quot;2 Exams&quot;, &quot;3 Exams&quot;, &quot;4 Exams&quot;, &quot;1 Exam&quot;, &quot;2...
## $ experience  &lt;dbl&gt; 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5...
## $ salary      &lt;chr&gt; &quot;48 - 65&quot;, &quot;50 - 71&quot;, &quot;54 - 77&quot;, &quot;58 - 82&quot;, &quot;54 - 72&quot;, ...
## $ salary_low  &lt;dbl&gt; 48, 50, 54, 58, 54, 57, 62, 63, 65, 70, 72, 85, 55, 58,...
## $ salary_high &lt;chr&gt; &quot;65&quot;, &quot;71&quot;, &quot;77&quot;, &quot;82&quot;, &quot;72&quot;, &quot;81&quot;, &quot;87&quot;, &quot;91&quot;, &quot;95&quot;, &quot;...</code></pre>
<ol style="list-style-type: decimal">
<li>How many industries are represented?</li>
<li>The <code>salary_high</code> column is a character type when it should be numeric. Change this column to numeric.</li>
<li>What are the highest and lowest salaries for an actuary in Health with 5 exams passed?</li>
<li>Create a new column called <code>salary_mid</code> which has the middle of the <code>salary_low</code> and <code>salary_high</code> columns.</li>
<li>When grouping by industry, what is the highest <code>salary_mid</code>? What about <code>salary_high</code>? What is the lowest <code>salary_low</code>?</li>
<li>There is a mistake when <code>salary_low == 11</code>. Find and fix this mistake, and then rerun the code from the previous task.</li>
<li>Create a new column, called <code>n_exams</code>, which is an integer. Use 7 for ASA/ACAS and 10 for FSA/FCAS. Use the code below as a starting point and fill in the <code>_</code> spaces</li>
<li>Create a column called <code>social_life</code>, which is equal to <code>n_exams</code>/<code>experience</code>. What is the average (mean) <code>social_life</code> by industry? Bonus question: what is wrong with using this as a statistical measure?</li>
</ol>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" title="1">actuary_salaries &lt;-<span class="st"> </span>actuary_salaries <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb201-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">n_exams =</span> <span class="kw">case_when</span>(exams <span class="op">==</span><span class="st"> &quot;FSA&quot;</span> <span class="op">~</span><span class="st"> </span>_,</a>
<a class="sourceLine" id="cb201-3" title="3">                             exams <span class="op">==</span><span class="st"> &quot;ASA&quot;</span> <span class="op">~</span><span class="st"> </span>_,</a>
<a class="sourceLine" id="cb201-4" title="4">                             exams <span class="op">==</span><span class="st"> &quot;FCAS&quot;</span> <span class="op">~</span><span class="st"> </span>_,</a>
<a class="sourceLine" id="cb201-5" title="5">                             exams <span class="op">==</span><span class="st"> &quot;ACAS&quot;</span> <span class="op">~</span><span class="st"> </span>_,</a>
<a class="sourceLine" id="cb201-6" title="6">                             <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">substr</span>(exams,_,_)))) </a></code></pre></div>
<ol start="8" style="list-style-type: decimal">
<li>Create a column called <code>social_life</code>, which is equal to <code>n_exams</code>/<code>experience</code>. What is the average (mean) <code>social_life</code> by industry? Bonus question: what is wrong with using this as a statistical measure?</li>
</ol>
</div>
<div id="answers-to-exercises" class="section level2">
<h2><span class="header-section-number">7.8</span> Answers to exercises</h2>
<p>Answers to these exercises, along with a video tutorial, are available at <a href="https://exampa.net/">ExamPA.net</a>.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="r-programming.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduction-to-modeling.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/sdcastillo/PA-R-Study-Manual/edit/master/03-data-exploration.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Exam-PA-Study-Manual.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
